services: 
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: example_pass
    ports:
      - "3307:3306"

  phpMyAdmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
